// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package stonks_api

import (
	context "context"
	empty "github.com/golang/protobuf/ptypes/empty"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// StonksApiClient is the client API for StonksApi service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type StonksApiClient interface {
	TelegramNotification(ctx context.Context, in *TelegramRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	GetCompanyStats(ctx context.Context, in *CompanyStatsRequest, opts ...grpc.CallOption) (*CompanyStatsResponse, error)
}

type stonksApiClient struct {
	cc grpc.ClientConnInterface
}

func NewStonksApiClient(cc grpc.ClientConnInterface) StonksApiClient {
	return &stonksApiClient{cc}
}

func (c *stonksApiClient) TelegramNotification(ctx context.Context, in *TelegramRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/StonksApi/TelegramNotification", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stonksApiClient) GetCompanyStats(ctx context.Context, in *CompanyStatsRequest, opts ...grpc.CallOption) (*CompanyStatsResponse, error) {
	out := new(CompanyStatsResponse)
	err := c.cc.Invoke(ctx, "/StonksApi/GetCompanyStats", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StonksApiServer is the server API for StonksApi service.
// All implementations must embed UnimplementedStonksApiServer
// for forward compatibility
type StonksApiServer interface {
	TelegramNotification(context.Context, *TelegramRequest) (*empty.Empty, error)
	GetCompanyStats(context.Context, *CompanyStatsRequest) (*CompanyStatsResponse, error)
	mustEmbedUnimplementedStonksApiServer()
}

// UnimplementedStonksApiServer must be embedded to have forward compatible implementations.
type UnimplementedStonksApiServer struct {
}

func (UnimplementedStonksApiServer) TelegramNotification(context.Context, *TelegramRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TelegramNotification not implemented")
}
func (UnimplementedStonksApiServer) GetCompanyStats(context.Context, *CompanyStatsRequest) (*CompanyStatsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCompanyStats not implemented")
}
func (UnimplementedStonksApiServer) mustEmbedUnimplementedStonksApiServer() {}

// UnsafeStonksApiServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StonksApiServer will
// result in compilation errors.
type UnsafeStonksApiServer interface {
	mustEmbedUnimplementedStonksApiServer()
}

func RegisterStonksApiServer(s grpc.ServiceRegistrar, srv StonksApiServer) {
	s.RegisterService(&StonksApi_ServiceDesc, srv)
}

func _StonksApi_TelegramNotification_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TelegramRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StonksApiServer).TelegramNotification(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/StonksApi/TelegramNotification",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StonksApiServer).TelegramNotification(ctx, req.(*TelegramRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StonksApi_GetCompanyStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CompanyStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StonksApiServer).GetCompanyStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/StonksApi/GetCompanyStats",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StonksApiServer).GetCompanyStats(ctx, req.(*CompanyStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// StonksApi_ServiceDesc is the grpc.ServiceDesc for StonksApi service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var StonksApi_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "StonksApi",
	HandlerType: (*StonksApiServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "TelegramNotification",
			Handler:    _StonksApi_TelegramNotification_Handler,
		},
		{
			MethodName: "GetCompanyStats",
			Handler:    _StonksApi_GetCompanyStats_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "stonks.proto",
}
